'use client';

import React from 'react';

import './globals.css';
// import { Inter } from 'next/font/google';
// import { Html } from 'next/document';
import Navbar from '@/components/Navbar';
import { ThemeProvider, createTheme } from '@mui/material';

// const inter = Inter({ subsets: ['latin'] });

const theme = createTheme({
  palette: {
    primary: {
      main: '#6600BF',
    },
  },
  components: {
    MuiButton: {},
  },
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body style={{ height: '100vh' }} className='bgImg fullscreen'>
        <ThemeProvider theme={theme}>
          <Navbar />
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
